# Generated by Django 5.0.7 on 2025-06-01 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helixai_app', '0002_remove_drugcomparisons_drugs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drugcomparisons',
            name='drug',
        ),
        migrations.AddField(
            model_name='drugcomparisons',
            name='drugs',
            field=models.ManyToManyField(null=True, related_name='drugs_to_drugs', to='helixai_app.drugs', verbose_name='Drugs'),
        ),
    ]
