# Generated by Django 5.0.7 on 2025-06-04 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helixai_app', '0003_remove_drugcomparisons_drug_drugcomparisons_drugs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drugeffects',
            name='drug',
        ),
        migrations.AddField(
            model_name='drugs',
            name='drug_effects',
            field=models.ManyToManyField(null=True, related_name='drug_to_effects', to='helixai_app.drugeffects', verbose_name='Drug Effects'),
        ),
        migrations.AlterField(
            model_name='drugcomparisons',
            name='drugs',
            field=models.ManyToManyField(null=True, related_name='+', to='helixai_app.drugs', verbose_name='Drugs'),
        ),
    ]
