# Generated by Django 5.0.7 on 2025-06-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helixai_app', '0004_remove_drugeffects_drug_drugs_drug_effects_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trials',
            name='side_effects',
        ),
        migrations.AddField(
            model_name='trials',
            name='drug_effects',
            field=models.ManyToManyField(blank=True, related_name='drug_effects_to_trials', to='helixai_app.drugs', verbose_name='Drug Effects'),
        ),
    ]
